In [22]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\dpuse\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dpuse\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dpuse\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dpuse\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\dpuse\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: C:\Users\dpuse\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [23]:
import pandas as pd

print(pd.__version__)

3.0.5

In [24]:
s = pd.Series([120, 85, 200, 45],
            index=["ene", "feb", "mar", "abr"],
            name="ventas")

print(s["mar"])

200

In [25]:
### DATA FRAME

import numpy as np

In [26]:
# a) Desde un diccionario de listas (la más habitual)
df = pd.DataFrame ({
    "producto" : ["Laptop", "Monitor" , "Teclado" ],
    "unidades" : [3, 7, 12],
    "precio": [1200.0, 320.0, 95.0],
    })

print(df)

  producto  unidades  precio
0   Laptop         3  1200.0
1  Monitor         7   320.0
2  Teclado        12    95.0

In [27]:
# b) Desde una lista de diccionarios (típico de una API JSON)
df2 = pd. DataFrame ([{"producto" : "Laptop", "unidades" : 3},
{"producto" : "Monitor" , "unidades" : 7}])

df2.head()

  producto  unidades
0   Laptop         3
1  Monitor         7

In [28]:
# c) Desde una lista de listas, indicando las columnas
df3 = pd. DataFrame ([["Laptop", 3], ["Monitor" , 7]],
columns=[ "producto" , "unidades" ])

df3.head()

  producto  unidades
0   Laptop         3
1  Monitor         7

In [29]:
# d) Desde un array de NumPy
df4 = pd. DataFrame (np.random.rand(3, 2), columns=[ "x", "y"])

df4.head()

          x         y
0  0.398752  0.456970
1  0.817721  0.315562
2  0.970012  0.455371

In [30]:
# \Users\dpuse\OneDrive\Documentos\datascience-g8
df = pd.read_csv(r"C:\Users\dpuse\OneDrive\Documentos\datascience-g8\ventas.csv")
df.head(n=10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450,0.0

In [31]:
df.tail(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1190,2024-12-29,Centro,Luis Gomez,Laptop Pro,Tecnologia,1,1200,0.10
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95,0.10
1193,2024-12-30,Centro,Ana Torres,Raton Ergo,Accesorios,7,45,0.00
1194,2024-12-30,Norte,Ana Torres,Tablet Air,Tecnologia,4,640,0.00
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   int64
 7   descuento        1165 non-null   float64
dtypes: float64(1), int64(2), str(5)
memory usage: 75.1 KB

In [33]:
df.describe()

          unidades  precio_unitario    descuento
count  1200.000000      1200.000000  1165.000000
mean      7.275833       387.412500     0.047639
std       4.054024       346.020316     0.056273
min       1.000000        45.000000     0.000000
25%       4.000000       130.000000     0.000000
50%       7.000000       280.000000     0.000000
75%      11.000000       450.000000     0.100000
max      14.000000      1200.000000     0.150000

In [34]:
df["unidades"].max()

np.int64(14)

In [35]:
df.describe()

          unidades  precio_unitario    descuento
count  1200.000000      1200.000000  1165.000000
mean      7.275833       387.412500     0.047639
std       4.054024       346.020316     0.056273
min       1.000000        45.000000     0.000000
25%       4.000000       130.000000     0.000000
50%       7.000000       280.000000     0.000000
75%      11.000000       450.000000     0.100000
max      14.000000      1200.000000     0.150000

In [37]:
df.sample(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
676,2024-07-26,Sur,Carlos Vega,Silla Ergo,Mobiliario,12,280,0.00
953,2024-10-17,Este,Elena Mora,Teclado Mec,Accesorios,12,95,0.10
107,2024-02-04,Norte,Ana Torres,Tablet Air,Tecnologia,10,640,0.10
252,2024-03-14,Sur,Luis Gomez,Escritorio,Mobiliario,13,450,0.00
305,2024-04-06,Centro,Sofia Leon,Escritorio,Mobiliario,5,450,0.05
855,2024-09-21,Sur,Pedro Diaz,Tablet Air,Tecnologia,3,640,0.00
706,2024-08-05,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.05
1133,2024-12-10,Oeste,Elena Mora,Auriculares,Accesorios,4,130,0.10
1110,2024-12-04,Norte,Pedro Diaz,Raton Ergo,Accesorios,12,45,0.05
1046,2024-11-09,Sur,Sofia Leon,Escritorio,Mobiliario,11,450,0.00

In [39]:
df.describe(include="object")

C:\Users\dpuse\AppData\Local\Temp\ipykernel_18540\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

             fecha region    vendedor    producto   categoria
count         1200   1200        1182        1200        1200
unique         349      5           8           8           3
top     2024-02-21  Norte  Marta Ruiz  Silla Ergo  Tecnologia
freq             9    305         170         177         447

In [40]:
df["region"].unique()

<StringArray>
['Oeste', 'Sur', 'Centro', 'Norte', 'Este']
Length: 5, dtype: str

In [42]:
df["region"].nunique()

5

In [43]:
df["region"].value_counts()

region
Norte     305
Centro    272
Sur       240
Oeste     203
Este      180
Name: count, dtype: int64

In [44]:
df["producto"].value_counts()

producto
Silla Ergo     177
Monitor 27     159
Auriculares    158
Tablet Air     149
Raton Ergo     146
Laptop Pro     139
Escritorio     139
Teclado Mec    133
Name: count, dtype: int64

In [47]:
df["producto"]

0       Auriculares
1        Monitor 27
2        Silla Ergo
3        Laptop Pro
4       Auriculares
           ...
1195     Raton Ergo
1196     Laptop Pro
1197     Monitor 27
1198     Monitor 27
1199     Raton Ergo
Name: producto, Length: 1200, dtype: str

In [48]:
df[["fecha", "region", "unidades"]]

           fecha  region  unidades
0     2024-01-02   Oeste         5
1     2024-01-02     Sur        14
2     2024-01-02  Centro         1
3     2024-01-02  Centro        10
4     2024-01-03     Sur         2
...          ...     ...       ...
1195  2024-12-30    Este         4
1196  2024-12-30    Este        13
1197  2024-12-31   Oeste         2
1198  2024-12-31   Norte         6
1199  2024-12-31   Norte         8

[1200 rows x 3 columns]

In [50]:
df.loc[0: 2, ["producto", "unidades"]]

      producto  unidades
0  Auriculares         5
1   Monitor 27        14
2   Silla Ergo         1

In [52]:
df.iloc[-1]

fecha              2024-12-31
region                  Norte
vendedor           Marta Ruiz
producto           Raton Ergo
categoria          Accesorios
unidades                    8
precio_unitario            45
descuento                 0.0
Name: 1199, dtype: object

In [54]:
df.sort_values("unidades", ascending=True)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
17,2024-01-06,Oeste,Marta Ruiz,Laptop Pro,Tecnologia,1,1200,0.00
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.00
54,2024-01-17,Norte,Luis Gomez,Silla Ergo,Mobiliario,1,280,0.00
491,2024-06-07,Centro,Ana Torres,Raton Ergo,Accesorios,1,45,0.15
...,...,...,...,...,...,...,...,...
62,2024-01-21,Este,Elena Mora,Silla Ergo,Mobiliario,14,280,0.00
63,2024-01-21,Este,Pedro Diaz,Silla Ergo,Mobiliario,14,280,0.10
75,2024-01-26,Sur,Luis Gomez,Escritorio,Mobiliario,14,450,0.00
828,2024-09-12,Centro,Ana Torres,Raton Ergo,Accesorios,14,45,0.05
841,2024-09-16,Sur,Carlos Vega,Teclado Mec,Accesorios,14,95,0.00

In [56]:
df.sort_values(["region", "unidades"], ascending=[True, False])

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
76,2024-01-27,Centro,Javier Sanz,Escritorio,Mobiliario,14,450,0.00
83,2024-01-30,Centro,Elena Mora,Auriculares,Accesorios,14,130,0.10
162,2024-02-19,Centro,Elena Mora,Monitor 27,Tecnologia,14,320,0.15
391,2024-04-30,Centro,Carlos Vega,Silla Ergo,Mobiliario,14,280,0.00
446,2024-05-23,Centro,Luis Gomez,Raton Ergo,Accesorios,14,45,0.05
...,...,...,...,...,...,...,...,...
1044,2024-11-09,Sur,Sofia Leon,Teclado Mec,Accesorios,1,95,0.10
1079,2024-11-26,Sur,Elena Mora,Tablet Air,Tecnologia,1,640,0.15
1094,2024-12-01,Sur,Marta Ruiz,Silla Ergo,Mobiliario,1,280,0.00
1104,2024-12-03,Sur,Pedro Diaz,Monitor 27,Tecnologia,1,320,0.05
1126,2024-12-08,Sur,Pedro Diaz,Escritorio,Mobiliario,1,450,0.00

In [57]:
df.sort_values("unidades", ascending=False).iloc[:5, :]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
420,2024-05-14,Este,Javier Sanz,Monitor 27,Tecnologia,14,320,0.10
309,2024-04-07,Norte,Elena Mora,Tablet Air,Tecnologia,14,640,0.05
607,2024-07-07,Centro,Javier Sanz,Auriculares,Accesorios,14,130,0.05
604,2024-07-05,Sur,Elena Mora,Laptop Pro,Tecnologia,14,1200,0.00
601,2024-07-05,Sur,Pedro Diaz,Monitor 27,Tecnologia,14,320,0.05

In [59]:
df.nlargest(5, "unidades")

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
62,2024-01-21,Este,Elena Mora,Silla Ergo,Mobiliario,14,280,0.0
63,2024-01-21,Este,Pedro Diaz,Silla Ergo,Mobiliario,14,280,0.1
75,2024-01-26,Sur,Luis Gomez,Escritorio,Mobiliario,14,450,0.0
76,2024-01-27,Centro,Javier Sanz,Escritorio,Mobiliario,14,450,0.0

In [60]:
# \Users\dpuse\OneDrive\Documentos\datascience-g8
df = pd.read_csv(r"C:\Users\dpuse\OneDrive\Documentos\datascience-g8\empleados.csv")
df.head(n=10)

,id_empleado,nombre,departamento,ciudad,salario,fecha_contratacion,evaluacion
0,1001,Marta Ruiz,Finanzas,Valencia,44300.0,2024-06-12,2.0
1,1002,Elena Sanz,RRHH,Madrid,22000.0,2022-08-16,1.0
2,1003,Ana Prieto,Ventas,Bilbao,58200.0,2024-02-21,4.0
3,1004,Laura Gomez,Marketing,Sevilla,24900.0,2023-05-21,3.0
4,1005,Paula Torres,RRHH,Madrid,54800.0,2019-01-18,5.0
5,1006,Lucia Mora,Finanzas,Valencia,49200.0,2022-03-25,3.0
6,1007,Javier Nieto,IT,Valencia,44400.0,2015-04-20,NaN
7,1008,Sergio Leon,Operaciones,Barcelona,28600.0,2020-07-01,2.0
8,1009,Lucia Nieto,Operaciones,Madrid,39700.0,2015-06-20,1.0
9,1010,Laura Lara,Finanzas,Sevilla,32800.0,2022-02-20,5.0